# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baad7d0dfe1972379cb9b61ecf98b3af4bf8fba1cab7f43a7094115bad20208aba7c7eeddaa46488b7cae473ff3d9e088fb94c6f6ac5062e66675c53f56b2e07

test:
  secret_key_base: fa4264995b125c547527edb278d3b9c750324ce9e24a91dbba4a04bbf60d50222a9cc1eecb3ea4d90f2b73fbb371e575db52d037e070dc53bc18fa9c8313ed0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
